import { z } from 'zod'
import { makeFirestoreConverter } from '../firestore/converter'
import { creditAccountIdSchema, creditStatementIdSchema, userIdSchema } from '../ids'
import { paiseSchema } from '../types/money'
import { epochMsSchema } from './common'

export const creditStatementStatusSchema = z.enum(['due', 'paid', 'overdue'])
export type CreditStatementStatus = z.infer<typeof creditStatementStatusSchema>

/**
 * One statement per billing cycle for a Khata credit account — design brief
 * item 7's "monthly statement function." Generated by
 * functions/src/credit/generateMonthlyStatement.ts; a Firestore doc only
 * (no PDF renderer this phase — see the Phase 12 plan's explicit scope cut).
 * `status` starts `due`, flips to `paid` when repayment brings
 * `creditAccounts.outstandingPaise` back under the pre-statement balance
 * (creditDueReminders.ts/autoBlockOverdueCredit.ts read it, never write
 * `paid` themselves — only applyCreditRepayment.ts does).
 */
export const creditStatementSchema = z.object({
  id: creditStatementIdSchema,
  creditAccountId: creditAccountIdSchema,
  buyerId: userIdSchema,
  periodFrom: epochMsSchema,
  periodTo: epochMsSchema,
  openingBalancePaise: paiseSchema,
  closingBalancePaise: paiseSchema,
  amountDuePaise: paiseSchema,
  dueDate: epochMsSchema,
  status: creditStatementStatusSchema,
  /** Set once creditDueReminders.ts sends the T-3-day reminder, so it's never sent twice for the same statement. */
  beforeReminderSentAt: epochMsSchema.optional(),
  /** Set once creditDueReminders.ts sends the overdue reminder (same run that flips status to 'overdue'). */
  overdueReminderSentAt: epochMsSchema.optional(),
  paidAt: epochMsSchema.optional(),
  createdAt: epochMsSchema,
  updatedAt: epochMsSchema,
})
export type CreditStatement = z.infer<typeof creditStatementSchema>

export const creditStatementConverter = makeFirestoreConverter(creditStatementSchema)
