// Generates public/sw.js — the single service worker for the whole app.
//
// It used to be scripts/generate-fcm-sw.mjs, emitting only the FCM
// background-push handler as public/firebase-messaging-sw.js. Phase 21 added
// offline caching, and a page can only ever be *controlled* by one service
// worker at a time — registering a second one at the same scope doesn't
// layer, it races — so the caching logic was folded into this same
// generated file instead of standing up a second SW. Firebase's config here
// is still read from apps/web/.env the same way, for the same reason as
// before: a static file served from public/ can't read import.meta.env.
//
// Run before `dev`/`build` (wired directly into those npm scripts, not a
// pre*/post* hook, since this repo doesn't enable pnpm's npm-style
// lifecycle hooks).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const webRoot = fileURLToPath(new URL('..', import.meta.url))
const envPath = `${webRoot}/.env`
const envSource = existsSync(envPath) ? readFileSync(envPath, 'utf8') : ''

function readEnv(name) {
  const match = envSource.match(new RegExp(`^${name}=(.*)$`, 'm'))
  return match ? match[1].trim() : ''
}

const firebaseConfig = {
  apiKey: readEnv('VITE_FIREBASE_API_KEY'),
  authDomain: readEnv('VITE_FIREBASE_AUTH_DOMAIN'),
  projectId: readEnv('VITE_FIREBASE_PROJECT_ID'),
  storageBucket: readEnv('VITE_FIREBASE_STORAGE_BUCKET'),
  messagingSenderId: readEnv('VITE_FIREBASE_MESSAGING_SENDER_ID'),
  appId: readEnv('VITE_FIREBASE_APP_ID'),
}
const swSource = `// AUTO-GENERATED by scripts/generate-sw.mjs — do not edit by hand.
// Firebase web config here is the same public, non-secret config
// apps/web/src/lib/firebase.ts uses (see Firebase console > Project
// settings > Your apps) — safe to ship in a static, publicly-served file.
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/11.0.2/firebase-messaging-compat.js');
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.1.0/workbox-sw.js');

firebase.initializeApp(${JSON.stringify(firebaseConfig, null, 2)});
const messaging = firebase.messaging();

// Background pushes (foreground ones are handled by onMessage in
// src/lib/pushNotifications.ts as a toast instead) — the browser shows the
// system notification itself from the payload's \`notification\` block;
// this only needs to react to the click.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const link = event.notification.data?.FCM_MSG?.data?.link || '/';
  event.waitUntil(clients.openWindow(link));
});

// ---- Offline / caching (Phase 21) ----------------------------------------
const OFFLINE_URL = '/offline.html';

workbox.core.setCacheNameDetails({ prefix: 'snapspare' });
workbox.core.skipWaiting();
workbox.core.clientsClaim();

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open('snapspare-offline-shell').then((cache) => cache.add(OFFLINE_URL)));
});

// Static build output (JS/CSS/fonts) — content-hashed by Vite, so a
// long-lived cache-first is safe: a new deploy ships new filenames rather
// than mutating these.
workbox.routing.registerRoute(
  ({ request }) => ['script', 'style', 'font'].includes(request.destination),
  new workbox.strategies.CacheFirst({
    cacheName: 'static-assets',
    plugins: [
      new workbox.expiration.ExpirationPlugin({ maxEntries: 120, maxAgeSeconds: 30 * 24 * 60 * 60 }),
      new workbox.cacheableResponse.CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
);

// Product/brand/category imagery — same-origin build assets and Firebase
// Storage-hosted images alike. Cache-first per the perf brief; the Resize
// Images extension gives each size its own filename, so a re-upload doesn't
// collide with a cached one.
workbox.routing.registerRoute(
  ({ request, url }) =>
    request.destination === 'image' || url.hostname === 'firebasestorage.googleapis.com',
  new workbox.strategies.CacheFirst({
    cacheName: 'product-images',
    plugins: [
      new workbox.expiration.ExpirationPlugin({ maxEntries: 300, maxAgeSeconds: 14 * 24 * 60 * 60 }),
      new workbox.cacheableResponse.CacheableResponsePlugin({ statuses: [0, 200] }),
    ],
  }),
);

// Typesense catalogue search — show the last result set instantly, then
// refresh it in the background, so browsing the catalogue stays fast on a
// flaky connection without ever going fully stale.
workbox.routing.registerRoute(
  ({ url }) => url.hostname.endsWith('.typesense.net'),
  new workbox.strategies.StaleWhileRevalidate({ cacheName: 'typesense-search' }),
);

// Cart, checkout and orders must never show a stale app shell — these are
// the screens where a wrong price or stock number is actually harmful, so
// they're explicitly network-only. (Registered before the catch-all
// navigation route below since Workbox uses first-match-wins.)
workbox.routing.registerRoute(
  ({ request, url }) =>
    request.mode === 'navigate' &&
    (url.pathname === '/cart' || url.pathname.startsWith('/checkout') || url.pathname.startsWith('/orders')),
  new workbox.strategies.NetworkOnly(),
);

// Every other navigation (home, categories, PDP, garage, store fronts):
// stale-while-revalidate so the app shell + last-seen content paints
// immediately offline/on a slow link, then updates underneath the buyer.
workbox.routing.registerRoute(
  ({ request }) => request.mode === 'navigate',
  new workbox.strategies.StaleWhileRevalidate({ cacheName: 'app-shell' }),
);

// If a navigation truly has no network and nothing cached to fall back to
// (including the network-only cart/checkout/orders routes above), show the
// offline page instead of the browser's default connection-error screen.
workbox.routing.setCatchHandler(async ({ event }) => {
  if (event.request.mode === 'navigate') {
    return caches.match(OFFLINE_URL);
  }
  return Response.error();
});
`

writeFileSync(`${webRoot}/public/sw.js`, swSource)
